// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOrWxYLYX_L_4u-SKwhiEifVjrLR8DTOY',
    appId: '1:551920917432:web:28ae12f91647ee98738d4d',
    messagingSenderId: '551920917432',
    projectId: 'gpt-card-analyzer',
    authDomain: 'gpt-card-analyzer.firebaseapp.com',
    storageBucket: 'gpt-card-analyzer.firebasestorage.app',
    measurementId: 'G-P67TJNSB8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBppXH9EUCohzeqMh3i2iiA8wb41lSa04c',
    appId: '1:551920917432:android:3c9a604037cc8779738d4d',
    messagingSenderId: '551920917432',
    projectId: 'gpt-card-analyzer',
    storageBucket: 'gpt-card-analyzer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1PBJeCeQ77U1hxqgsgDWEy-dhD8FogNw',
    appId: '1:551920917432:ios:d25090a3fb89a549738d4d',
    messagingSenderId: '551920917432',
    projectId: 'gpt-card-analyzer',
    storageBucket: 'gpt-card-analyzer.firebasestorage.app',
    iosBundleId: 'com.example.gptCardAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1PBJeCeQ77U1hxqgsgDWEy-dhD8FogNw',
    appId: '1:551920917432:ios:d25090a3fb89a549738d4d',
    messagingSenderId: '551920917432',
    projectId: 'gpt-card-analyzer',
    storageBucket: 'gpt-card-analyzer.firebasestorage.app',
    iosBundleId: 'com.example.gptCardAnalyzer',
  );
}
